### PR TITLE
i386 toolchain + script quality

### PR DESCRIPTION
**Pull request by mykola2312**
This PR enables building of i386 32-bit toolchain. Why would we need 32-bit toolchain? I must say that many people, including me, rely on this project as a toolchain bootstrap and find it useful for our different needs. Yes, it will increase build-time of toolchain, but on the bright with i386 toolchain many users could begin their journey into OS development very easy. I saw someone is making docker image of toolchain and I think it should be complete with 32-bit GCC as well.

Props to You for keeping all required patches for i386 in place.

For me personally, I need i386 toolchain to compile C code into 16 bit real-mode compatible way, and only i386 toolchain can do this.

This PR will be ground for my future bootloader I'm making for cavOS. You can see some funny stuff going in [mbr4ext2](https://github.com/mykola2312/mbr4ext2)

Aside from toolchain changes, Makefile is no more doing ```chmod +x``` on scripts in order to execute them, but rather directly calls ```$(SH)``` (which is by default set to ```bash```) to execute script. This is the right way to execute & source scripts. I must mention that changing file permissions in git repo will lead to strange git changes, if git config ```core.fileMode``` is not set to ```false```. So, starting from this PR, I advise You to always use ```bash <script.sh>``` instead of ```chmod +x script.sh``` + ```./script.sh```.

I have fixed bug where autotools check won't add them from ~/opt because it only did in if block, I moved it outside and now it always uses ~/opt version whenever possible, resolving cryptic autoconf issues.

Also, I moved commands like ```qemu-system-x86_64``` to their respective variables like ```$(QEMU)```, as well as formatted Makefile so it doesn't look ugly.

I many times tested ```make tools``` as well as ```make qemu``` and it works.

Sincerely,
[mykola2312](https://github.com/mykola2312/)

### CODE REVIEW

**Comment by malwarepad** [comment]
Wow, this is like the first big PR I've seen submitted to any of my projects, really appreciate it :p

Regardless, I don't want to provide a 32-bit cross compiler since I can `-m32` at any point without much trouble. If people want such a compiler for their own projects, they can either follow the osdev wiki themselves or modify the tools scripts that I provide accordingly. As you pointed out yourself, I've kept the patches there exactly as a helper hand for those people (although that's beyond the scope of the repo)

Furthermore, I only took a slight peak at the file diffs and the "beauty" fixes just make readability worse and are not up to the standard of my codebase. Indentation changes like that are not to my liking (personally) and I believe that there are far more important "beautification" changes to be done, especially in the `ports.sh` `cross_compile.sh` dependency which is horridly written.

Just so you don't waste your time, I will not accept a handwritten/alternative bootloader to Limine for the time being, no matter the featureset. I really second Limine's mindset, stability and ease of use (direct long mode drop, simple menus, limited features, etc), while it's developed by a large sum of experienced low level developers. I don't want to give up any of those for the privilege of a "custom bootloader" which is (in my opinion) just useless boilerplate.

**Comment by mykola2312** [comment]
> Wow, this is like the first big PR I've seen submitted to any of my projects, really appreciate it :p
> 
> Regardless, I don't want to provide a 32-bit cross compiler since I can `-m32` at any point without much trouble. If people want such a compiler for their own projects, they can either follow the osdev wiki themselves or modify the tools scripts that I provide accordingly. As you pointed out yourself, I've kept the patches there exactly as a helper hand for those people (although that's beyond the scope of the repo)
> 
> Furthermore, I only took a slight peak at the file diffs and the "beauty" fixes just make readability worse and are not up to the standard of my codebase. Indentation changes like that are not to my liking (personally) and I believe that there are far more important "beautification" changes to be done, especially in the `ports.sh` `cross_compile.sh` dependency which is horridly written.
> 
> Just so you don't waste your time, I will not accept a handwritten/alternative bootloader to Limine for the time being, no matter the featureset. I really second Limine's mindset, stability and ease of use (direct long mode drop, simple menus, limited features, etc), while it's developed by a large sum of experienced low level developers. I don't want to give up any of those for the privilege of a "custom bootloader" which is (in my opinion) just useless boilerplate.

Well, You just killed all my hopes, now it pointless to do bootloader... But I expected such response. Well, "useless boilerplate" is BSD-2Clause license which limine licensed with. What a shame.

 > ```-m32```
 No, this won't work. You explicitly need i386 toolchain target to be able to compile C into real-mode compatible machine instructions.

**Comment by malwarepad** [comment]
I'm sorry for killing your hope, but I've told you multiple times in chats I think. Thanks for the time making that, it's not to waste since you probably learned a lot along the ride.

Regarding limine, I personally don't have any problems with BSD-2Clause.

**Comment by mykola2312** [comment]
Farewell.

**Comment by h4rldev** [comment]
BSD 3-Clause is better imo, it's my preferred license

**Pull request closed without merging**
